[package]
name = "a86mcore"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ping = "0.4.1"
hurl = "4.0.0"
lettre = "0.10.4"
influxdb = "0.7.0"
serde_json = "1.0.104"
serde = "1.0.178"
